version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: wavetechteam
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
        ports:
            - 8000:80
        environment:
            - APP_ENV=production
            - APP_DEBUG=true
            - APP_KEY=base64:N07x9RUNJOLVIXc0v9IM3vXUmC4d5vLQEsLcr2r8wtA=
            # Configuration base de données avec des variables dynamiques
            - DB_HOST=db # Nom du service de la base de données
            - DB_PORT=3306 # Port de la base de données
            - DB_DATABASE=wavetechteam # Nom de la base de données
            - DB_USERNAME=root # Nom d'utilisateur de la base
            - DB_PASSWORD=fKoiuYEGHkBAUUhEBqndqobMBHqXINWV # Mot de passe de la base
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: wavetechteam-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: fKoiuYEGHkBAUUhEBqndqobMBHqXINWV
            MYSQL_DATABASE: wavetechteam # Base de données à créer
            MYSQL_USER: root
            MYSQL_PASSWORD: fKoiuYEGHkBAUUhEBqndqobMBHqXINWV
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql

    nginx:
        image: nginx:latest
        container_name: wavetechteam-nginx
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        depends_on:
            - app

volumes:
    db-data: {}
